const MODELOS = {
  // ── PILOTOS ───────────────────────────────────────────────────────────────
  // Coleção nova recebida da modelista em 28/08/2026, ainda em pilotagem: o molde do
  // Audaces tem UM tamanho só (P, M ou base), a grade PP–GG ainda não foi feita.
  // `tecido`, `consumo`, `preco` e `cores` ficam VAZIOS de propósito — número chutado
  // aqui vira metragem errada na ficha de compra e custo errado na costura. Preencher
  // quando a peça voltar da prova, e então mover a linha para o grupo definitivo.
  // Croqui, arquivo .adsx e medidas ficam na aba MODELAGEM (projetos 390007–390015).
  // A imagem do croqui traz frente E costas no mesmo desenho, por isso só croquiFrente.
  'vestido-sereia':{nome:'Vestido Sereia',tecido:'',consumo:0,preco:0,componentes:'1 Frente – 1 Costas – 1 Gola',obs:'PILOTO — molde tamanho P, sem grade. Pesponto na reta. Gola de ribana com colocação em anel. Viés na cava. Barra de galoneira de 2cm.',cores:[],aberto:{},croquiFrente:'/croqui-vestido-sereia.jpg?v=2026082801'},
  'vestido-bolso':{nome:'Vestido com Bolso',tecido:'',consumo:0,preco:0,componentes:'1 Frente – 1 Costas – 4 Bolsos – 2 Forros Frente/Costas',obs:'PILOTO — molde tamanho base, sem grade. Decote e cava duplos. Bolso embutido. Abertura na barra (frente e costas). Barra de galoneira de 2 viras de 1cm.',cores:[],aberto:{},croquiFrente:'/croqui-vestido-bolso.jpg?v=2026082801'},
  'saia-longa-bolso-faca':{nome:'Saia Longa com Bolso Faca',tecido:'',consumo:0,preco:0,componentes:'1 Frente – 2 Costas – 2 Bolsos – 2 Espelhos de Bolso – 1 Cós',obs:'PILOTO — molde tamanho base, sem grade. Cós franzido com 72cm de elástico. Bolso faca. Abertura de 40cm. Barra limpa na overlock.',cores:[],aberto:{},croquiFrente:'/croqui-saia-longa-bolso-faca.jpg?v=2026082801'},
  'mini-saia-envelope':{nome:'Mini Saia Envelope',tecido:'',consumo:0,preco:0,componentes:'1 Saia – 2 Laços – 1 Cós',obs:'PILOTO — molde tamanho base, sem grade. Cós costurado na overlock com pesponto na reta. Etiqueta da marca no cós, atrás. Barra limpa na overlock.',cores:[],aberto:{},croquiFrente:'/croqui-mini-saia-envelope.jpg?v=2026082801'},
  'top-basico':{nome:'Top Básico',tecido:'',consumo:0,preco:0,componentes:'2 Frentes – 2 Costas – 2 Alças',obs:'PILOTO — molde tamanho P, sem grade. Peça toda dupla. Alça em rolote. Elástico de 0,5cm embutido na barra.',cores:[],aberto:{},croquiFrente:'/croqui-top-basico.jpg?v=2026082801'},
  'top-v':{nome:'Top V',tecido:'',consumo:0,preco:0,componentes:'2 Frentes – 2 Costas',obs:'PILOTO — molde tamanho P, sem grade. Peça toda dupla. Viés de 3cm. Costura do V feita na máquina reta. Bainha de 4cm.',cores:[],aberto:{},croquiFrente:'/croqui-top-v.jpg?v=2026082801'},
  'top-laco':{nome:'Top Laço',tecido:'',consumo:0,preco:0,componentes:'4 Frentes – 2 Costas – 2 Alças',obs:'PILOTO — molde tamanho M, sem grade. Top todo duplo. Alça em rolote. Laço amarrado na frente.',cores:[],aberto:{},croquiFrente:'/croqui-top-laco.jpg?v=2026082801'},
  'blusa-basica':{nome:'Blusa Básica',tecido:'',consumo:0,preco:0,componentes:'1 Frente – 1 Costas – 2 Alças – 2 Forros Frente – 1 Forro Costas',obs:'PILOTO — molde tamanho P, sem grade. Alça em rolote. Pesponto interno na galoneira. Forro da frente duplo com elástico de 0,5cm. Forro fica solto na barra.',cores:[],aberto:{},croquiFrente:'/croqui-blusa-basica.jpg?v=2026082801'},

  // ── MACACÕES ──────────────────────────────────────────────────────────────
  'macacao-amplo':{nome:'Macacão Amplo',tecido:'Viscose',consumo:1.8,preco:28,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Cós – 1 Zíper',obs:'Verificar alinhamento do tecido antes do corte. Manter margem de costura de 1cm.',cores:['Preto','Off White','Marrom','Militar','Roxo','Marsala'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Roxo':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-macacao-amplo-frente.jpg?v=2026060804',croquiCostas:'/croqui-macacao-amplo-costas.jpg?v=2026060804'},
  'macacao-manga-longa':{nome:'Macacão Manga Longa',tecido:'Crepe',consumo:2.1,preco:32,componentes:'2 Frentes – 1 Costas – 2 Mangas Longas – 1 Cós',obs:'',cores:['Preto','Off White','Marrom','Militar'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},

  // ── MACAQUINHOS ───────────────────────────────────────────────────────────
  'macaquinho-amplo':{nome:'Macaquinho Amplo',tecido:'Viscose',consumo:1.5,preco:28,componentes:'2 Frentes – 1 Costas – 1 Cós',obs:'',cores:['Preto','Off White','Marsala','Petróleo','Azul Baby','Militar','Marrom','Nude'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Petróleo':[0,0,0,0,0],'Azul Baby':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-macaquinho-amplo-frente.jpg',croquiCostas:'/croqui-macaquinho-amplo-costas.jpg'},
  'macaquinho-ruel':{nome:'Macaquinho Ruel',tecido:'Malha',consumo:1.2,preco:22,componentes:'2 Frentes – 1 Costas',obs:'',cores:['Off White','Marsala','Fúcsia','Azul Baby'],aberto:{'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Fúcsia':[0,0,0,0,0],'Azul Baby':[0,0,0,0,0]},croquiFrente:'/croqui-macaquinho-ruel-frente.jpg?v=2026061601'},

  // ── VESTIDOS ──────────────────────────────────────────────────────────────
  'vestido-frente-unica-longo':{nome:'Vestido Frente Única Longo',tecido:'Crepe',consumo:2.0,preco:32,componentes:'1 Frente – 1 Costas – 2 Alças',obs:'',tamanhoUnico:true,cores:['Preto','Militar','Off White','Marsala','Petróleo'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Petróleo':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-frente-unica-longo-frente.jpg?v=2026060806',croquiCostas:'/croqui-vestido-frente-unica-longo-costas.jpg?v=2026060806'},
  'vestido-frente-unica-curto':{nome:'Vestido Frente Única Curto',tecido:'Crepe',consumo:1.4,preco:32,componentes:'1 Frente – 1 Costas – 2 Alças',obs:'',tamanhoUnico:true,cores:['Preto','Militar','Off White'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Off White':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-frente-unica-curto-frente.jpg?v=2026060807',croquiCostas:'/croqui-vestido-frente-unica-curto-costas.jpg?v=2026060807'},
  'vestido-amplo':{nome:'Vestido Amplo',tecido:'Viscose',consumo:1.9,preco:28,componentes:'2 Frentes – 1 Costas',obs:'',cores:['Telha','Azul','Marrom','Roxo','Preto','Militar'],aberto:{'Telha':[0,0,0,0,0],'Azul':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Roxo':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-amplo-frente.jpg?v=2026061601'},

  // ── CONJUNTOS ─────────────────────────────────────────────────────────────
  'conjunto-peace':{nome:'Conjunto Peace',tecido:'Viscolycra',consumo:1.6,preco:12,componentes:'4 Frentes – 2 Costas – 2 Mangas',obs:'',cores:['Nude','Preto','Off White','Marsala'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0]}},
  'conjunto-wide':{nome:'Conjunto Wide',tecido:'Linho',consumo:2.2,preco:36,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'conjunto-boho':{nome:'Conjunto Boho',tecido:'Viscose Est.',consumo:1.7,preco:30,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Nude','Mescla','Marinho'],tamanhos:['PP','P','M','G','GG','G1'],aliasCores:{'Cinza':'Mescla'},aberto:{'Nude':[0,0,0,0,0],'Mescla':[0,0,0,0,0],'Marinho':[0,0,0,0,0]},croquiFrente:'/croqui-conjunto-boho-frente.jpg',croquiCostas:'/croqui-conjunto-boho-costas.jpg?v=2026061601'},
  'conjunto-canelado':{nome:'Conjunto Canelado',tecido:'Canelado',consumo:1.5,preco:19,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Preto','Militar','Telha','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'conjunto-calca-flare-camiseta':{nome:'Conjunto Calça Flare + Camiseta Oversized',tecido:'Canelado/Malha',consumo:2.4,preco:37,componentes:'',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'conjunto-calca-flare-moletom':{nome:'Conjunto Calça Flare + Moletom Gola Alta',tecido:'Canelado/Moletom',consumo:2.8,preco:44,componentes:'',obs:'',cores:['Cinza','Militar','Marrom','Nude'],aberto:{'Cinza':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'conjunto-calca-pantalona-moletom':{nome:'Conjunto Calça Pantalona + Moletom Gola Alta',tecido:'Moletom',consumo:2.8,preco:27.5,componentes:'',obs:'',cores:['Nude','Rosa Baby'],aberto:{'Nude':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0]}},
  'conjunto-calca-pantalona-cropped':{nome:'Conjunto Calça Pantalona + Cropped Moletom',tecido:'Moletom',consumo:2.5,preco:27.5,componentes:'',obs:'',cores:['Cinza','Preto','Vermelho','Marrom'],tamanhos:['PP','P','M','G','GG','G1'],aberto:{'Cinza':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'conjunto-cozy':{nome:'Conjunto Cozy',tecido:'Moletom',consumo:3.1,preco:27.5,componentes:'',obs:'Calça Pantalona Moletom + Moletom Zíper com Bolsos. Bordô (Marsala), Preto e Marrom.',cores:['Marsala','Preto','Marrom','Cinza'],aberto:{'Marsala':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Cinza':[0,0,0,0,0]}},
  'conjunto-mood':{nome:'Conjunto Mood',tecido:'Moletom',consumo:2.8,preco:27.5,componentes:'',obs:'Moletom Zíper com Bolsos + Calça Básica Moletom (reta). Marrom e Marsala.',cores:['Marrom','Marsala'],aberto:{'Marrom':[0,0,0,0,0],'Marsala':[0,0,0,0,0]}},
  // Conjunto Good = Short Good + Regata Good, em moletom CARECA (não é o moletom comum).
  // Separado em peças a pedido da Bárbara em 03/09/2026 — o pedido #8991 caía em
  // "produto não mapeado" e ficava fora da conta de produção. Cores e grade vêm da loja
  // (Preto e Vermelho, PP–GG). Consumo/preço são a SOMA das duas peças e estão estimados.
  'conjunto-good':{nome:'Conjunto Good',tecido:'Moletom Careca',consumo:1.7,preco:27.5,componentes:'',obs:'Short Good + Regata Good, em moletom careca. Consumo/preço estimados — ajustar com o dado real.',cores:['Preto','Vermelho'],aberto:{'Preto':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},
  'conjunto-moletom-saia-midi':{nome:'Conjunto Moletom Gola Alta + Saia Midi',tecido:'Moletom/Canelado',consumo:2.5,preco:44,componentes:'',obs:'',cores:['Preto','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'conjunto-moletom-short-bolso':{nome:'Conjunto Moletom Gola Alta + Short Bolso Frontal',tecido:'Moletom',consumo:2.9,preco:27.5,componentes:'',obs:'Moletom Gola Alta + Calça/Short Bolso Frontal. Preto.',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},
'conjunto-pantalona-blusa':{nome:'Conjunto Pantalona + Blusa Canelada',tecido:'Moletom/Canelado',consumo:2.5,preco:44,componentes:'',obs:'',cores:['Nude','Preto'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'conjunto-regata-mini-saia':{nome:'Conjunto Regata Oversized + Mini Saia Canelada',tecido:'Malha/Canelado',consumo:1.5,preco:35,componentes:'',obs:'',cores:['Off White','Preto'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'conjunto-camiseta-mini-saia':{nome:'Conjunto Camiseta Oversized + Mini Saia Canelada',tecido:'Malha/Canelado',consumo:1.8,preco:38,componentes:'',obs:'Combinações: "Verde Militar + Preta" = camiseta Militar + saia Preto; "Marsala + Nude" = camiseta Marsala + saia Nude.',cores:['Preto','Militar','Verde Militar + Preta','Marsala + Nude'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Verde Militar + Preta':[0,0,0,0,0],'Marsala + Nude':[0,0,0,0,0]}},
  'conjunto-canguru-longo':{nome:'Conjunto Canguru Longo',tecido:'Moletom',consumo:2.5,preco:27.5,componentes:'',obs:'',cores:['Off White','Telha'],aberto:{'Off White':[0,0,0,0,0],'Telha':[0,0,0,0,0]}},
  'conjunto-saia-midi-oversized':{nome:'Conjunto Saia Midi + Oversized',tecido:'Canelado/Malha',consumo:1.8,preco:40,componentes:'',obs:'',cores:['Off White'],aberto:{'Off White':[0,0,0,0,0]}},
  'conjunto-calca-bolso-camiseta':{nome:'Conjunto Calça Bolso Frontal + Camiseta Oversized',tecido:'Moletom/Malha',consumo:2.0,preco:40,componentes:'',obs:'Calça Off White + Camiseta Preta',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},

  // ── SAIAS ─────────────────────────────────────────────────────────────────
  'saia-midi':{nome:'Saia Midi',tecido:'Canelado',consumo:1.0,preco:19,componentes:'',obs:'',cores:['Preto','Marrom','Off White','Marrom Claro'],aberto:{'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom Claro':[0,0,0,0,0]},croquiFrente:'/croqui-saia-midi-frente.jpg?v=2026061601'},
  'mini-saia-canelada':{nome:'Mini Saia Canelada',tecido:'Canelado',consumo:0.6,preco:19,componentes:'2 Frentes – 1 Cós',obs:'',cores:['Preto','Off White','Branco','Militar','Marrom','Marsala','Nude'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Branco':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},

  // ── CALÇAS ────────────────────────────────────────────────────────────────
  'calca-pantalona':{nome:'Calça Pantalona Moletom',tecido:'Moletom',consumo:1.3,preco:27.5,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos',obs:'',cores:['Nude','Preto','Rosa Baby','Cinza','Marsala','Vermelho','Marrom'],tamanhos:['PP','P','M','G','GG','G1'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Marrom':[0,0,0,0,0]},croquiFrente:'/croqui-calca-pantalona-frente.jpg',croquiCostas:'/croqui-calca-pantalona-costas.jpg'},
  'calca-basica-moletom':{nome:'Calça Básica Moletom',tecido:'Moletom',consumo:1.3,preco:27.5,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Preto','Nude','Cinza','Marrom','Off White','Marsala','Telha'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Telha':[0,0,0,0,0]}},
  'calca-pantalona-viscolycra':{nome:'Calça Pantalona Viscolycra',tecido:'Viscolycra',consumo:1.3,preco:12,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos',obs:'',cores:['Preto','Nude','Cinza','Militar','Uva','Off White','Rosa Baby','Marsala'],tamanhos:['PP','P','M','G','GG','G1'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Uva':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-calca-pantalona-viscolycra-frente.jpg',croquiCostas:'/croqui-calca-pantalona-viscolycra-costas.jpg'},
  'calca-flare':{nome:'Calça Flare Canelada',tecido:'Canelado',consumo:1.4,preco:19,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Nude','Preto','Marsala','Telha','Cinza','Marrom','Militar'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0]},croquiFrente:'/croqui-calca-flare-frente.jpg?v=2026061601'},
  'calca-peace':{nome:'Calça Peace',tecido:'Viscolycra',consumo:1.2,preco:12,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Marsala','Off White','Preto','Nude'],aberto:{'Marsala':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-calca-peace-frente.jpg',croquiCostas:'/croqui-calca-peace-costas.jpg'},
  'calca-bolso-frontal':{nome:'Calça Bolso Frontal',tecido:'Moletom',consumo:1.3,preco:27.5,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos Frontais',obs:'',cores:['Off White','Preto'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  // Peças do Conjunto Boho (separadas em 04/08/2026 a pedido da Bárbara — o conjunto passou a
  // distribuir para as duas). Consumo e preço dividem os do conjunto (2,5m e R$30) e são estimados:
  // ajustar quando tiver o dado real de cada peça. Grade vai até G1, igual à do conjunto.
  'calca-boho':{nome:'Calça Boho',tecido:'Viscose Est.',consumo:1.5,preco:18,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos Frontais',obs:'Corte reto, bolsos frontais amplos, cós liso na frente e ajustado atrás. Consumo/preço estimados (divididos do conjunto) — ajustar com o dado real.',cores:['Nude','Mescla','Marinho'],tamanhos:['PP','P','M','G','GG','G1'],aliasCores:{'Cinza':'Mescla'},aberto:{'Nude':[0,0,0,0,0,0],'Mescla':[0,0,0,0,0,0],'Marinho':[0,0,0,0,0,0]}},

  // Peça de baixo do Conjunto Good (moletom CARECA). Consumo e preço de costura estimados
  // pelo padrão das peças de moletom do cadastro — ajustar quando vier o dado real.
  'short-good':{nome:'Short Good',tecido:'Moletom Careca',consumo:0.8,preco:27.5,componentes:'',obs:'Peça do Conjunto Good. Moletom careca. Consumo/preço estimados — ajustar com o dado real.',cores:['Preto','Vermelho'],aberto:{'Preto':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},

  // ── CASACOS ───────────────────────────────────────────────────────────────
  'casaco-sherpa':{nome:'Casaco Sherpa',tecido:'Sherpa',consumo:1.8,preco:35,componentes:'',obs:'',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},
  'casaco-sherpa-capuz':{nome:'Casaco Sherpa com Capuz',tecido:'Sherpa',consumo:2.0,preco:40,componentes:'',obs:'Preto: pedido manual personalizado',cores:['Telha','Vermelho','Preto'],aberto:{'Telha':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'casaco-pele-persa':{nome:'Casaco Pele Persa Xadrez',tecido:'Pele Persa',consumo:1.8,preco:40,componentes:'',obs:'',cores:['Azul','Marrom'],aberto:{'Azul':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'carneirinho-cropped':{nome:'Carneirinho Cropped',tecido:'Carneirinho',consumo:1.5,preco:35,componentes:'',obs:'',cores:['Off White','Preto','Telha'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Telha':[0,0,0,0,0]}},
  'sherpa-ziper-bolsos':{nome:'Sherpa com Zíper (Casaco Bear)',tecido:'Sherpa',consumo:2.3,preco:20,componentes:'2 Frentes – 2 Costas – 4 Mangas – 1 Gola',obs:'Peça quando for de sherpa será todo duplo',cores:['Off White','Marrom','Preto'],aberto:{'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Preto':[0,0,0,0,0]},croquiFrente:'/croqui-sherpa-ziper-frente.jpg',croquiCostas:'/croqui-sherpa-ziper-costas.jpg'},

  // ── TOPS/BLUSAS ───────────────────────────────────────────────────────────
  'camiseta-oversized':{nome:'Camiseta Oversized',tecido:'Malha',consumo:1.0,preco:18,componentes:'1 Frente – 1 Costas – 2 Mangas',obs:'',cores:['Off White','Preto','Nude','Militar','Marsala'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-camiseta-oversized-frente.jpg?v=2026061601'},
  'blusa-canelada-simples':{nome:'Blusa Canelada',tecido:'Canelado',consumo:0.9,preco:19,componentes:'1 Frente – 1 Costas – 2 Mangas',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'blusa-canelada':{nome:'Blusa Canelada Punho Dedinho',tecido:'Canelado',consumo:1.0,preco:19,componentes:'1 Frente – 1 Costas – 2 Mangas – Punho',obs:'',cores:['Off White','Preto','Marrom','Telha','Militar'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},
  'regata-oversized':{nome:'Regata Oversized',tecido:'Malha',consumo:0.8,preco:15,componentes:'1 Frente – 1 Costas',obs:'',cores:['Preto','Off White'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0]}},
  'cropped-mini-saia':{nome:'Cropped + Mini Saia Canelada',tecido:'Canelado',consumo:1.2,preco:19,componentes:'',obs:'',cores:['Preto','Off White','Branco','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Branco':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'cropped-canelado':{nome:'Cropped Canelado',tecido:'Canelado',consumo:0.6,preco:19,componentes:'1 Frente – 1 Costas',obs:'',cores:['Preto','Off White','Branco','Marrom','Nude','Cinza'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Branco':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-cropped-canelado-frente.jpg?v=2026061601'},

  'cropped-peace':{nome:'Cropped Peace',tecido:'Viscolycra',consumo:0.6,preco:12,componentes:'',obs:'',cores:['Nude','Preto','Off White','Marsala'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-cropped-peace-frente.jpg',croquiCostas:'/croqui-cropped-peace-costas.jpg'},

  'cropped-moletom':{nome:'Cropped Moletom',tecido:'Moletom',consumo:0.8,preco:27.5,componentes:'',obs:'',cores:['Cinza','Preto','Nude','Marrom','Off White','Vermelho'],tamanhos:['PP','P','M','G','GG','G1'],aberto:{'Cinza':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},

  'cropped-frente-unica':{nome:'Cropped Frente Única',tecido:'Suplex',consumo:0.6,preco:20,componentes:'',obs:'Consumo/preço estimados (mesmo padrão dos outros croppeds) — ajustar quando tiver dado real.',cores:['Royal','Preto','Militar'],aberto:{'Royal':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},
  // Par da 'calca-boho' — as duas juntas formam o Conjunto Boho.
  'blusa-boho':{nome:'Blusa Boho',tecido:'Viscose Est.',consumo:1.0,preco:12,componentes:'2 Frentes – 1 Costas',obs:'Modelagem despojada, ombro levemente caído, recortes frontais. Consumo/preço estimados (divididos do conjunto) — ajustar com o dado real.',cores:['Nude','Mescla','Marinho'],tamanhos:['PP','P','M','G','GG','G1'],aliasCores:{'Cinza':'Mescla'},aberto:{'Nude':[0,0,0,0,0,0],'Mescla':[0,0,0,0,0,0],'Marinho':[0,0,0,0,0,0]}},

  // Par do 'short-good' — as duas juntas formam o Conjunto Good.
  'regata-good':{nome:'Regata Good',tecido:'Moletom Careca',consumo:0.9,preco:27.5,componentes:'',obs:'Peça do Conjunto Good. Moletom careca. Consumo/preço estimados — ajustar com o dado real.',cores:['Preto','Vermelho'],aberto:{'Preto':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},

  // ── SAPATOS ───────────────────────────────────────────────────────────────
  'flat':{nome:'Flat',tecido:'',consumo:0,preco:0,componentes:'',obs:'',revenda:true,tamanhos:['34','35','36','37','38','39','40'],cores:['Preto','Off White'],aberto:{'Preto':[0,0,0,0,0,0,0],'Off White':[0,0,0,0,0,0,0]}},
  'sandalia-gladiadora':{nome:'Sandália Gladiadora',tecido:'',consumo:0,preco:0,componentes:'',obs:'Calçado / revenda (não produzido na confecção)',revenda:true,tamanhos:['34','35','36','37','38','39','40'],cores:['Preto','Nude/Marrom'],aliasCores:{'Bege':'Nude/Marrom'},aberto:{'Preto':[0,0,0,0,0,0,0],'Nude/Marrom':[0,0,0,0,0,0,0]}},

  // ── OUTROS ────────────────────────────────────────────────────────────────
  'canguru-amplo':{nome:'Canguru Amplo',tecido:'Moletom',consumo:1.8,preco:27.5,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Capuz – 2 Bolsos',obs:'',cores:['Preto','Off White','Branco','Cinza','Marrom','Nude','Telha'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Branco':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Telha':[0,0,0,0,0]}},
  'moletom-gola-alta':{nome:'Moletom Gola Alta',tecido:'Moletom',consumo:1.6,preco:27.5,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Gola',obs:'',cores:['Nude','Marrom','Preto','Rosa Baby','Militar','Vermelho','Cinza'],aberto:{'Nude':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Cinza':[0,0,0,0,0]}},
  'moletom-ziper-bolsos':{nome:'Moletom Zíper com Bolsos',tecido:'Moletom',consumo:1.5,preco:27.5,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Gola',obs:'Peça quando for de moletom terá frente dupla para o zíper',cores:['Off White','Preto','Marrom','Marsala','Cinza'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Cinza':[0,0,0,0,0]},croquiFrente:'/croqui-moletom-ziper-frente.jpg',croquiCostas:'/croqui-moletom-ziper-costas.jpg'},
};

const SIDEBAR_ESTRUTURA = [
  // Fica no topo e separado de propósito: peça em pilotagem não pode ser confundida
  // com peça de produção na hora de mandar corte/compra. Quando o piloto for aprovado,
  // a chave sai daqui e entra no grupo definitivo (VESTIDOS, SAIAS, TOPS...).
  {titulo:'PILOTOS',     modelos:['vestido-sereia','vestido-bolso','saia-longa-bolso-faca','mini-saia-envelope','top-basico','top-v','top-laco','blusa-basica']},
  {titulo:'MACACÕES',    modelos:['macacao-amplo','macacao-manga-longa']},
  {titulo:'MACAQUINHOS', modelos:['macaquinho-amplo','macaquinho-ruel']},
  {titulo:'VESTIDOS',    modelos:['vestido-frente-unica-longo','vestido-frente-unica-curto','vestido-amplo']},
  {titulo:'CALÇAS',      modelos:['calca-pantalona','calca-basica-moletom','calca-pantalona-viscolycra','calca-flare','calca-peace','calca-bolso-frontal','calca-boho','short-good']},
  {titulo:'CASACOS',     modelos:['casaco-sherpa','casaco-sherpa-capuz','casaco-pele-persa','carneirinho-cropped','sherpa-ziper-bolsos']},
  {titulo:'TOPS',        modelos:['camiseta-oversized','blusa-canelada-simples','blusa-canelada','regata-oversized','cropped-canelado','cropped-moletom','cropped-peace','cropped-frente-unica','blusa-boho','regata-good']},
  {titulo:'SAIAS',       modelos:['saia-midi','mini-saia-canelada']},
  {titulo:'SAPATOS',     modelos:['flat','sandalia-gladiadora']},
  {titulo:'OUTROS',      modelos:['moletom-gola-alta','moletom-ziper-bolsos','canguru-amplo']},
  {titulo:'CONJUNTOS',   modelos:['conjunto-peace','conjunto-wide','conjunto-boho','conjunto-canelado','conjunto-calca-flare-moletom','conjunto-calca-flare-camiseta','conjunto-calca-pantalona-moletom','conjunto-calca-pantalona-cropped','conjunto-cozy','conjunto-mood','conjunto-moletom-saia-midi','conjunto-pantalona-blusa','conjunto-regata-mini-saia','conjunto-camiseta-mini-saia','cropped-mini-saia','conjunto-canguru-longo','conjunto-saia-midi-oversized','conjunto-calca-bolso-camiseta','conjunto-moletom-short-bolso','conjunto-good']},
];
