const MODELOS = {
  // ── MACACÕES ──────────────────────────────────────────────────────────────
  'macacao-amplo':{nome:'Macacão Amplo',tecido:'Viscose',consumo:1.8,preco:28,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Cós – 1 Zíper',obs:'Verificar alinhamento do tecido antes do corte. Manter margem de costura de 1cm.',cores:['Preto','Off White','Marrom','Militar','Roxo','Marsala'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Roxo':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-macacao-amplo-frente.jpg?v=2026060804',croquiCostas:'/croqui-macacao-amplo-costas.jpg?v=2026060804'},
  'macacao-manga-longa':{nome:'Macacão Manga Longa',tecido:'Crepe',consumo:2.1,preco:32,componentes:'2 Frentes – 1 Costas – 2 Mangas Longas – 1 Cós',obs:'',cores:['Preto','Off White','Marrom','Militar'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},

  // ── MACAQUINHOS ───────────────────────────────────────────────────────────
  'macaquinho-amplo':{nome:'Macaquinho Amplo',tecido:'Viscose',consumo:1.5,preco:28,componentes:'2 Frentes – 1 Costas – 1 Cós',obs:'',cores:['Preto','Off White','Marsala','Petróleo','Azul Baby','Militar','Marrom','Nude'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Petróleo':[0,0,0,0,0],'Azul Baby':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-macaquinho-amplo-frente.jpg',croquiCostas:'/croqui-macaquinho-amplo-costas.jpg'},
  'macaquinho-ruel':{nome:'Macaquinho Ruel',tecido:'Malha',consumo:1.2,preco:22,componentes:'2 Frentes – 1 Costas',obs:'',cores:['Off White','Marsala','Fúcsia','Azul Baby'],aberto:{'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Fúcsia':[0,0,0,0,0],'Azul Baby':[0,0,0,0,0]},croquiFrente:'/croqui-macaquinho-ruel-frente.jpg?v=2026061601'},

  // ── VESTIDOS ──────────────────────────────────────────────────────────────
  'vestido-frente-unica-longo':{nome:'Vestido Frente Única Longo',tecido:'Crepe',consumo:2.0,preco:32,componentes:'1 Frente – 1 Costas – 2 Alças',obs:'',tamanhoUnico:true,cores:['Preto','Militar','Off White','Marsala','Petróleo'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Petróleo':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-frente-unica-longo-frente.jpg?v=2026060806',croquiCostas:'/croqui-vestido-frente-unica-longo-costas.jpg?v=2026060806'},
  'vestido-frente-unica-curto':{nome:'Vestido Frente Única Curto',tecido:'Crepe',consumo:1.4,preco:32,componentes:'1 Frente – 1 Costas – 2 Alças',obs:'',tamanhoUnico:true,cores:['Preto','Militar','Off White'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Off White':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-frente-unica-curto-frente.jpg?v=2026060807',croquiCostas:'/croqui-vestido-frente-unica-curto-costas.jpg?v=2026060807'},
  'vestido-amplo':{nome:'Vestido Amplo',tecido:'Viscose',consumo:1.9,preco:28,componentes:'2 Frentes – 1 Costas',obs:'',cores:['Telha','Azul','Marrom','Roxo','Preto','Militar'],aberto:{'Telha':[0,0,0,0,0],'Azul':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Roxo':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0]},croquiFrente:'/croqui-vestido-amplo-frente.jpg?v=2026061601'},

  // ── CONJUNTOS ─────────────────────────────────────────────────────────────
  'conjunto-peace':{nome:'Conjunto Peace',tecido:'Canelado',consumo:1.6,preco:24,componentes:'4 Frentes – 2 Costas – 2 Mangas',obs:'',cores:['Nude','Preto','Off White','Marsala'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0]}},
  'conjunto-wide':{nome:'Conjunto Wide',tecido:'Linho',consumo:2.2,preco:36,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'conjunto-boho':{nome:'Conjunto Boho',tecido:'Viscose Est.',consumo:1.7,preco:30,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Nude','Mescla','Marinho'],aberto:{'Nude':[0,0,0,0,0],'Mescla':[0,0,0,0,0],'Marinho':[0,0,0,0,0]},croquiFrente:'/croqui-conjunto-boho-frente.jpg',croquiCostas:'/croqui-conjunto-boho-costas.jpg?v=2026061601'},
  'conjunto-canelado':{nome:'Conjunto Canelado',tecido:'Canelado',consumo:1.5,preco:24,componentes:'4 Frentes – 2 Costas',obs:'',cores:['Preto','Militar','Telha','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'conjunto-calca-flare-moletom':{nome:'Conjunto Calça Flare + Moletom Gola Alta',tecido:'Canelado/Moletom',consumo:2.8,preco:44,componentes:'',obs:'',cores:['Cinza','Militar','Marrom','Nude'],aberto:{'Cinza':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'conjunto-calca-pantalona-moletom':{nome:'Conjunto Calça Pantalona + Moletom Gola Alta',tecido:'Moletom',consumo:2.8,preco:40,componentes:'',obs:'',cores:['Nude','Rosa Baby'],aberto:{'Nude':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0]}},
  'conjunto-calca-pantalona-cropped':{nome:'Conjunto Calça Pantalona + Cropped Moletom',tecido:'Moletom',consumo:2.5,preco:44,componentes:'',obs:'',cores:['Cinza','Preto','Vermelho'],aberto:{'Cinza':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},
  'conjunto-cozy':{nome:'Conjunto Cozy',tecido:'Moletom',consumo:3.1,preco:48,componentes:'',obs:'Calça Pantalona Moletom + Moletom Zíper com Bolsos. Bordô (Marsala).',cores:['Marsala'],aberto:{'Marsala':[0,0,0,0,0]}},
  'conjunto-mood':{nome:'Conjunto Mood',tecido:'Moletom',consumo:2.8,preco:25,componentes:'',obs:'Moletom Zíper com Bolsos + Calça Básica Moletom (reta). Marrom.',cores:['Marrom'],aberto:{'Marrom':[0,0,0,0,0]}},
  'conjunto-moletom-saia-midi':{nome:'Conjunto Moletom Gola Alta + Saia Midi',tecido:'Moletom/Canelado',consumo:2.5,preco:44,componentes:'',obs:'',cores:['Preto','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'conjunto-moletom-short-bolso':{nome:'Conjunto Moletom Gola Alta + Short Bolso Frontal',tecido:'Moletom',consumo:2.9,preco:42,componentes:'',obs:'Moletom Gola Alta + Calça/Short Bolso Frontal. Preto.',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},
'conjunto-pantalona-blusa':{nome:'Conjunto Pantalona + Blusa Canelada',tecido:'Moletom/Canelado',consumo:2.5,preco:44,componentes:'',obs:'',cores:['Nude','Preto'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'conjunto-regata-mini-saia':{nome:'Conjunto Regata Oversized + Mini Saia Canelada',tecido:'Malha/Canelado',consumo:1.5,preco:35,componentes:'',obs:'',cores:['Off White','Preto'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'conjunto-camiseta-mini-saia':{nome:'Conjunto Camiseta Oversized + Mini Saia Canelada',tecido:'Malha/Canelado',consumo:1.8,preco:38,componentes:'',obs:'',cores:['Preto','Militar'],aberto:{'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},
  'conjunto-canguru-longo':{nome:'Conjunto Canguru Longo',tecido:'Moletom',consumo:2.5,preco:50,componentes:'',obs:'',cores:['Off White'],aberto:{'Off White':[0,0,0,0,0]}},
  'conjunto-saia-midi-oversized':{nome:'Conjunto Saia Midi + Oversized',tecido:'Canelado/Malha',consumo:1.8,preco:40,componentes:'',obs:'',cores:['Off White'],aberto:{'Off White':[0,0,0,0,0]}},
  'conjunto-calca-bolso-camiseta':{nome:'Conjunto Calça Bolso Frontal + Camiseta Oversized',tecido:'Moletom/Malha',consumo:2.0,preco:40,componentes:'',obs:'Calça Off White + Camiseta Preta',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},

  // ── SAIAS ─────────────────────────────────────────────────────────────────
  'saia-midi':{nome:'Saia Midi',tecido:'Canelado',consumo:1.0,preco:20,componentes:'',obs:'',cores:['Preto','Marrom','Off White','Marrom Claro'],aberto:{'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom Claro':[0,0,0,0,0]},croquiFrente:'/croqui-saia-midi-frente.jpg?v=2026061601'},
  'mini-saia-canelada':{nome:'Mini Saia Canelada',tecido:'Canelado',consumo:0.6,preco:20,componentes:'2 Frentes – 1 Cós',obs:'',cores:['Preto','Off White','Militar','Marrom','Marsala','Nude'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},

  // ── CALÇAS ────────────────────────────────────────────────────────────────
  'calca-pantalona':{nome:'Calça Pantalona Moletom',tecido:'Moletom',consumo:1.3,preco:20,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos',obs:'',cores:['Nude','Preto','Rosa Baby','Cinza','Marsala','Vermelho'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]},croquiFrente:'/croqui-calca-pantalona-frente.jpg',croquiCostas:'/croqui-calca-pantalona-costas.jpg'},
  'calca-basica-moletom':{nome:'Calça Básica Moletom',tecido:'Moletom',consumo:1.3,preco:20,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Preto','Nude','Cinza','Marrom','Off White'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0]}},
  'calca-pantalona-viscolycra':{nome:'Calça Pantalona Viscolycra',tecido:'Viscolycra',consumo:1.3,preco:20,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos',obs:'',cores:['Preto','Nude','Cinza','Militar','Uva','Off White','Rosa Baby','Marsala'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Uva':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-calca-pantalona-viscolycra-frente.jpg',croquiCostas:'/croqui-calca-pantalona-viscolycra-costas.jpg'},
  'calca-flare':{nome:'Calça Flare Canelada',tecido:'Canelado',consumo:1.4,preco:24,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Nude','Preto','Marsala','Telha','Cinza','Marrom','Militar'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marsala':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Militar':[0,0,0,0,0]},croquiFrente:'/croqui-calca-flare-frente.jpg?v=2026061601'},
  'calca-peace':{nome:'Calça Peace',tecido:'Moletom',consumo:1.3,preco:22,componentes:'2 Frentes – 2 Costas – 1 Cós',obs:'',cores:['Marsala','Off White','Preto','Nude'],aberto:{'Marsala':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-calca-peace-frente.jpg',croquiCostas:'/croqui-calca-peace-costas.jpg'},
  'calca-bolso-frontal':{nome:'Calça Bolso Frontal',tecido:'Moletom',consumo:1.3,preco:22,componentes:'2 Frentes – 2 Costas – 1 Cós – 2 Bolsos Frontais',obs:'',cores:['Off White','Preto'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},

  // ── CASACOS ───────────────────────────────────────────────────────────────
  'casaco-sherpa':{nome:'Casaco Sherpa',tecido:'Sherpa',consumo:1.8,preco:35,componentes:'',obs:'',cores:['Preto'],aberto:{'Preto':[0,0,0,0,0]}},
  'casaco-sherpa-capuz':{nome:'Casaco Sherpa com Capuz',tecido:'Sherpa',consumo:2.0,preco:40,componentes:'',obs:'Preto: pedido manual personalizado',cores:['Telha','Vermelho','Preto'],aberto:{'Telha':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'casaco-pele-persa':{nome:'Casaco Pele Persa Xadrez',tecido:'Pele Persa',consumo:1.8,preco:40,componentes:'',obs:'',cores:['Azul','Marrom'],aberto:{'Azul':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'carneirinho-cropped':{nome:'Carneirinho Cropped',tecido:'Carneirinho',consumo:1.5,preco:35,componentes:'',obs:'',cores:['Off White','Preto'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0]}},
  'sherpa-ziper-bolsos':{nome:'Sherpa com Zíper (Casaco Bear)',tecido:'Sherpa',consumo:2.3,preco:20,componentes:'2 Frentes – 2 Costas – 4 Mangas – 1 Gola',obs:'Peça quando for de sherpa será todo duplo',cores:['Off White','Marrom','Preto'],aberto:{'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Preto':[0,0,0,0,0]},croquiFrente:'/croqui-sherpa-ziper-frente.jpg',croquiCostas:'/croqui-sherpa-ziper-costas.jpg'},

  // ── TOPS/BLUSAS ───────────────────────────────────────────────────────────
  'camiseta-oversized':{nome:'Camiseta Oversized',tecido:'Malha',consumo:1.0,preco:18,componentes:'1 Frente – 1 Costas – 2 Mangas',obs:'',cores:['Off White','Preto','Nude','Militar','Marsala'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-camiseta-oversized-frente.jpg?v=2026061601'},
  'blusa-canelada-simples':{nome:'Blusa Canelada',tecido:'Canelado',consumo:0.9,preco:20,componentes:'1 Frente – 1 Costas – 2 Mangas',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'blusa-canelada':{nome:'Blusa Canelada Punho Dedinho',tecido:'Canelado',consumo:1.0,preco:22,componentes:'1 Frente – 1 Costas – 2 Mangas – Punho',obs:'',cores:['Off White','Preto','Marrom','Telha','Militar'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Telha':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},
  'regata-oversized':{nome:'Regata Oversized',tecido:'Malha',consumo:0.8,preco:15,componentes:'1 Frente – 1 Costas',obs:'',cores:['Preto','Off White'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0]}},
  'regata-canelada':{nome:'Regata Canelada',tecido:'Canelado',consumo:0.7,preco:15,componentes:'1 Frente – 1 Costas',obs:'',cores:['Preto','Nude'],aberto:{'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0]}},
  'cropped-mini-saia':{nome:'Cropped + Mini Saia Canelada',tecido:'Canelado',consumo:1.2,preco:25,componentes:'',obs:'',cores:['Preto','Off White','Marrom'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0]}},
  'cropped-canelado':{nome:'Cropped Canelado',tecido:'Canelado',consumo:0.6,preco:20,componentes:'1 Frente – 1 Costas',obs:'',cores:['Preto','Off White','Marrom','Nude'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0]},croquiFrente:'/croqui-cropped-canelado-frente.jpg?v=2026061601'},

  'cropped-peace':{nome:'Cropped Peace',tecido:'Canelado',consumo:0.8,preco:20,componentes:'',obs:'',cores:['Nude','Preto','Off White','Marsala'],aberto:{'Nude':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-cropped-peace-frente.jpg',croquiCostas:'/croqui-cropped-peace-costas.jpg'},

  'cropped-moletom':{nome:'Cropped Moletom',tecido:'Moletom',consumo:0.8,preco:20,componentes:'',obs:'',cores:['Cinza','Preto','Nude','Marrom','Off White','Vermelho'],aberto:{'Cinza':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Vermelho':[0,0,0,0,0]}},

  'cropped-frente-unica':{nome:'Cropped Frente Única',tecido:'Suplex',consumo:0.6,preco:20,componentes:'',obs:'Consumo/preço estimados (mesmo padrão dos outros croppeds) — ajustar quando tiver dado real.',cores:['Royal','Preto','Militar'],aberto:{'Royal':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Militar':[0,0,0,0,0]}},

  // ── SAPATOS ───────────────────────────────────────────────────────────────
  'flat':{nome:'Flat',tecido:'',consumo:0,preco:0,componentes:'',obs:'',revenda:true,tamanhos:['34','35','36','37','38','39','40'],cores:['Preto','Off White'],aberto:{'Preto':[0,0,0,0,0,0,0],'Off White':[0,0,0,0,0,0,0]}},
  'sandalia-gladiadora':{nome:'Sandália Gladiadora',tecido:'',consumo:0,preco:0,componentes:'',obs:'Calçado / revenda (não produzido na confecção)',revenda:true,tamanhos:['34','35','36','37','38','39','40'],cores:['Preto','Marrom','Nude/Marrom'],aberto:{'Preto':[0,0,0,0,0,0,0],'Marrom':[0,0,0,0,0,0,0],'Nude/Marrom':[0,0,0,0,0,0,0]}},

  // ── OUTROS ────────────────────────────────────────────────────────────────
  'canguru-amplo':{nome:'Canguru Amplo',tecido:'Moletom',consumo:1.8,preco:30,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Capuz – 2 Bolsos',obs:'',cores:['Preto','Off White','Cinza','Marrom','Nude','Telha'],aberto:{'Preto':[0,0,0,0,0],'Off White':[0,0,0,0,0],'Cinza':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Nude':[0,0,0,0,0],'Telha':[0,0,0,0,0]}},
  'moletom-gola-alta':{nome:'Moletom Gola Alta',tecido:'Moletom',consumo:1.6,preco:20,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Gola',obs:'',cores:['Nude','Marrom','Preto','Rosa Baby','Militar','Vermelho','Cinza'],aberto:{'Nude':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Rosa Baby':[0,0,0,0,0],'Militar':[0,0,0,0,0],'Vermelho':[0,0,0,0,0],'Cinza':[0,0,0,0,0]}},
  'moletom-ziper-bolsos':{nome:'Moletom Zíper com Bolsos',tecido:'Moletom',consumo:1.5,preco:29,componentes:'2 Frentes – 1 Costas – 2 Mangas – 1 Gola',obs:'Peça quando for de moletom terá frente dupla para o zíper',cores:['Off White','Preto','Marrom','Marsala'],aberto:{'Off White':[0,0,0,0,0],'Preto':[0,0,0,0,0],'Marrom':[0,0,0,0,0],'Marsala':[0,0,0,0,0]},croquiFrente:'/croqui-moletom-ziper-frente.jpg',croquiCostas:'/croqui-moletom-ziper-costas.jpg'},
};

const SIDEBAR_ESTRUTURA = [
  {titulo:'MACACÕES',    modelos:['macacao-amplo','macacao-manga-longa']},
  {titulo:'MACAQUINHOS', modelos:['macaquinho-amplo','macaquinho-ruel']},
  {titulo:'VESTIDOS',    modelos:['vestido-frente-unica-longo','vestido-frente-unica-curto','vestido-amplo']},
  {titulo:'CALÇAS',      modelos:['calca-pantalona','calca-basica-moletom','calca-pantalona-viscolycra','calca-flare','calca-peace','calca-bolso-frontal']},
  {titulo:'CASACOS',     modelos:['casaco-sherpa','casaco-sherpa-capuz','casaco-pele-persa','carneirinho-cropped','sherpa-ziper-bolsos']},
  {titulo:'TOPS',        modelos:['camiseta-oversized','blusa-canelada-simples','blusa-canelada','regata-oversized','regata-canelada','cropped-canelado','cropped-moletom','cropped-peace','cropped-frente-unica']},
  {titulo:'SAIAS',       modelos:['saia-midi','mini-saia-canelada']},
  {titulo:'SAPATOS',     modelos:['flat','sandalia-gladiadora']},
  {titulo:'OUTROS',      modelos:['moletom-gola-alta','moletom-ziper-bolsos','canguru-amplo']},
  {titulo:'CONJUNTOS',   modelos:['conjunto-peace','conjunto-wide','conjunto-boho','conjunto-canelado','conjunto-calca-flare-moletom','conjunto-calca-pantalona-moletom','conjunto-calca-pantalona-cropped','conjunto-cozy','conjunto-mood','conjunto-moletom-saia-midi','conjunto-pantalona-blusa','conjunto-regata-mini-saia','conjunto-camiseta-mini-saia','cropped-mini-saia','conjunto-canguru-longo','conjunto-saia-midi-oversized','conjunto-calca-bolso-camiseta','conjunto-moletom-short-bolso']},
];
